version: '3.9'

services:
  frontend:
    build: ./frontend
    command: "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: npm run start:dev
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
